namespaces:
  - name: allowed-namespace-1
    group: group-1
    resources:
      requests:
        memory: 1Gi
        cpu: 1
      limits:
        memory: 2Gi
        cpu: 2
  - name: allowed-namespace-2
    group: group-2
    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 3Gi
        cpu: 3
defaultNamespaces:
  - default
  - gatekeeper-system                                                 
  - kube-node-lease                                                   
  - kube-public                                                       
  - kube-system                                                                                                 
  - multicluster-monitoring                                           
  - ocp411-dev                                                        
  - opa-exporter                                                      
  - open-cluster-management-agent                                     
  - open-cluster-management-agent-addon                               
  - openshift                                                         
  - openshift-apiserver                                               
  - openshift-apiserver-operator                                    
  - openshift-authentication                                          
  - openshift-authentication-operator                                 
  - openshift-cloud-controller-manager                                
  - openshift-cloud-controller-manager-operator                       
  - openshift-cloud-credential-operator                               
  - openshift-cloud-network-config-controller                         
  - openshift-cluster-csi-drivers                                     
  - openshift-cluster-machine-approver                                
  - openshift-cluster-node-tuning-operator                            
  - openshift-cluster-samples-operator                                
  - openshift-cluster-storage-operator                                
  - openshift-cluster-version                                         
  - openshift-config                                                  
  - openshift-config-managed                                          
  - openshift-config-operator                                         
  - openshift-console                                                 
  - openshift-console-operator                                        
  - openshift-console-user-settings                                   
  - openshift-controller-manager                                      
  - openshift-controller-manager-operator                             
  - openshift-dns                                                     
  - openshift-dns-operator                                            
  - openshift-etcd                                                    
  - openshift-etcd-operator                                           
  - openshift-gitops                                                  
  - openshift-host-network                                            
  - openshift-image-registry                                          
  - openshift-infra                                                   
  - openshift-ingress                                                 
  - openshift-ingress-canary                                          
  - openshift-ingress-operator                                        
  - openshift-insights                                                
  - openshift-kni-infra                                               
  - openshift-kube-apiserver                                          
  - openshift-kube-apiserver-operator                                 
  - openshift-kube-controller-manager                                 
  - openshift-kube-controller-manager-operator                        
  - openshift-kube-scheduler                        
  - openshift-kube-scheduler-operator               
  - openshift-kube-storage-version-migrator         
  - openshift-kube-storage-version-migrator-operator
  - openshift-machine-api                           
  - openshift-machine-config-operator               
  - openshift-marketplace                           
  - openshift-monitoring                            
  - openshift-multus                                
  - openshift-network-diagnostics                   
  - openshift-network-operator                      
  - openshift-node                                  
  - openshift-nutanix-infra                         
  - openshift-oauth-apiserver                       
  - openshift-openstack-infra                       
  - openshift-operator-lifecycle-manager            
  - openshift-operators                             
  - openshift-ovirt-infra                           
  - openshift-route-controller-manager              
  - openshift-sdn                                   
  - openshift-service-ca                            
  - openshift-service-ca-operator                   
  - openshift-user-workload-monitoring              
  - openshift-vsphere-infra
  - managed-namespace
  - openshift-storage
  - openshift-local-storage