namespaces:
  - name: allowed-namespace-1
    group: group-1
    resources:
      requests:
        memory: 1Gi
        cpu: 1
      limits:
        memory: 2Gi
        cpu: 2
  - name: allowed-namespace-2
    group: group-2
    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 3Gi
        cpu: 3
defaultNamespaces:
  - default