apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-management
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          state: 'managed'
  template:
    metadata:
      name: 'namespace-management-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/michaelkotelnikov/gitops-governance.git
        targetRevision: master
        path: charts/gitops-governance/
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
