apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespace-management
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-namespace-management'
    spec:
      project: default
      source:
        repoURL: https://github.com/michaelkotelnikov/gitops-governance.git
        targetRevision: master
        path: charts/gitops-governance/
      destination:
        name: '{{server}}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true