{
 "title": "Namespace Management System",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Unmanaged namespaces in the environment over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(opa_scorecard_constraint_violations)",
     "legendFormat": "Unmanaged Namespaces in the environment"
    }
   ]
  },
  {
   "title": "Number of violations by cluster",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(opa_scorecard_constraint_violations) by (cluster_name)",
     "legendFormat": "Unmanaged Namespaces in the environment"
    }
   ]
  },
  {
   "title": "Total unmanaged namespaces in the environment",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "opa_scorecard_constraint_violations",
     "legendFormat": "Unmanaged Namespaces in the environment"
    }
   ]
  }
 ]
}