apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisallowNamespaces
metadata:
  name: disallow-namespaces
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    allowedNamespaces:
      {{- include "allowedNamespaces" . | nindent 6 }}