{{- range $namespace := .Values.namespaces -}}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $namespace.name }}-rolebinding
  namespace: {{ $namespace.name }}
subjects:
- kind: Group
  name: {{ $namespace.group }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
{{ end }}