apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDisallowNamespaces
metadata:
  name: disallow-namespaces
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    allowedNamespaces:
      {{- include "allowedNamespaces" . | trim | nindent 6 }}
